name: Executar Script de Aniversário

on:
  schedule:
    - cron: "25 01 * * *" # Executa todos os dias às 01:25 UTC (22:25 BRT)
    - cron: "30 01 * * *" # Executa todos os dias às 01:30 UTC (22:30 BRT)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true

    - name: Definir variáveis de ambiente
      run: |
        echo "EMAIL_LOGIN=${{ secrets.EMAIL_LOGIN }}" >> $GITHUB_ENV
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

    - name: Executar Script
      run: python script.py
