name: Executar Script de Aniversário

on:
  schedule:
    - cron: "10 22 * * *" # Executa todos os dias às 22:10
    - cron: "20 22 * * *" # Executa todos os dias às 22:20

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # Instala dependências se existir o arquivo requirements.txt

    - name: Executar Script
      run: python seu_script.py
